[project]
name = "42roma-monitor"
version = "0.1.0"
description = "42 Roma Monitor"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
]

[dependency-groups]
lint = [
    "ruff>=0.14.9",
]
